# ==========================================
# CryptoVerse API Service
# ==========================================
apiVersion: v1
kind: Service
metadata:
  name: cryptoverse-api-service
  namespace: cryptoverse
  labels:
    app.kubernetes.io/name: cryptoverse-api
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cryptoverse-api
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 3001
      targetPort: http
      protocol: TCP
  sessionAffinity: None