# ==========================================
# CryptoVerse Frontend Service
# ==========================================
apiVersion: v1
kind: Service
metadata:
  name: cryptoverse-frontend-service
  namespace: cryptoverse
  labels:
    app.kubernetes.io/name: cryptoverse-frontend
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cryptoverse-frontend
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  sessionAffinity: None